[project]
name = "python-circuit-breaker"
version = "0.1.0"
description = "A simple circuit breaker implementation"
readme = "README.md"
requires-python = ">=3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
